name: kubeimage

on: 
 push:
  branches: [master]
jobs:
 build:
  runs-on: ubuntu-latest
   services:
      redis:
        # Docker Hub image
        image: redis
        ports:
          - 6379:6379
        credentials:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_password }}
      db:
        # Private registry image
        image:  ghcr.io/octocat/testdb:latest
        credentials:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ghcr_password }}
           IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
