name: Python CI

on:
  push:
    branches:
      - master  # or the branch you want to trigger the workflow on

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Replace with your Python version
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Packages
        run: echo "${{ secrets.SECRET_GITHUBAC }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64 -t docker.pkg.github.com/${{ github.repository_owner }}/${{ github.repository_name }}/my-python-app:latest .
          docker push docker.pkg.github.com/${{ github.repository_owner }}/${{ github.repository_name }}/my-python-app:latest 

