name: ci integeration
on: 
 push: 
  branches: [master]
 pull_request: 
  branches: [master]
jobs: 
 build-and-test:
  runs-on: ubuntu-latest
  steps: 
  - uses: actions/checkout@v4
    name: check out source code
  - name: set up python
    uses: actions/setup-python@v4
    with: 
     python-version: '3.x'
  - name: install python dependencies
    run: pytest tests/

  - name: build docker image
    run: |
     docker build -t python:3
  - name: log in to the container registry
    uses: docker/login-action@v3
    with: 
     registry: ${{ env.REGISTRY }}
     username: ${{ github.actor }}
     password: ${{ secrets.SECRET_GITHUBAC }}
  - name: push docker image to registry
    run: |
     docker push python:3 
