name: ci docker
on: 
 push: 
  branches: [main]
jobs: 
 container-test-job: 
  runs-on: ubuntu-latest
  container: 
   image: node:16
   env: 
    NODE_ENV: development
   ports: 
    - 80
   volumes: 
   - my_docker_volume:/volume_mount
   options: --cpus 1
  steps: 
   - name: check for dockerfile
     run: (is /.dockerenv $$ echo Found dockerenv) || (echoNO dockerenv)
