name: publish a docker image
on: 
 push: 
  branches: [master]
env: 
 REGISTRY: ghcr.io
 IMAGE_NAME: ${{ github.repository }}

jobs: 
 build-and-push-image:
  runs-on: ubuntu-latest

  permissions: 
   contents: read
   packages: write
   attestations: write
   id-token: write

  steps: 
   - name: checkout repository
     uses: actions/checkout@4
     with: 
      show-progress: true

   - name: log in to the container registry
     uses: docker/login-action@v3.2.0
     with: 
      registry: ${{ env.REGISTRY }}
      username: ${{ github.actor }}
      password: ${{ secrets.SECRET_GITHUBAC }}
   - name: Docker metadata (tags, labels)
     id: meta
     uses: docker/metadata-action@v5.5.1
     with:
      images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
   - name: Build and push Docker images
     id: push
     uses: docker/build-push-action@v5.4.0
     with: 
      context: .
      push: true
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
