name: Build and Push Docker image to Docker Hub

on: push
jobs:
  build_and_publish:
    name: Push Docker image to github package
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Build and push Docker image
        run: |
         dockerlogin --username Bansidhar03 --password ${{ SECRET_GITHUB }} ghcr.io
         docker build . --tag ghcr.io/Bansidhar03/node.js:14
         docker push ghcr.io/Bansidhar03/node.js:14
