name: Build/Push Docker Image

on: 
 push: 
   branch: master
   pull_request: master

   jobs: 
    build: 

    runs-on: ubuntu-latest
    
    steps: 
     - uses: actions/checkout@4
     - name: use node.js
       uses: action/setip-node@4
       with:
        node-version: ['17.9.0']
     - name: install dependencies
       run: npm install
     - run: npm run build --if -present
     - run: npm test
  
       
