name: cloud-api

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        id: login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          # Extract the repository name from the environment variable
          REPO_NAME=${{ github.repository }}
          # Remove any trailing dashes and convert to lowercase
          # The 'sed' command removes trailing dashes
          # The 'tr' command converts the repository name to lowercase, ensuring it complies with Docker tag requirements
          CLEAN_REPO_NAME=$(echo "$REPO_NAME" | sed 's/-$//' | tr '[:upper:]' '[:lower:]')
          # Build and push the Docker image with cleaned-up repository name
          docker build -t ghcr.io/$CLEAN_REPO_NAME/nodejs-app:latest .
          docker push ghcr.io/$CLEAN_REPO_NAME/nodejs-app:latest
        env:
          # Ensure that the GITHUB_TOKEN is passed to Docker commands
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
