name: Build and Push Docker image to Docker Hub 

on: push
jobs:
  build_and_publish:
    name: Push Docker image to github package
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Build and push Docker image
        run: |
         docker login --username bansidhar03 --password ${{ secrets.SECRET_GITHUBAC }} ghcr.io
         docker build . --tag ghcr.io/bansidhar03/python:3.12.3
         docker push ghcr.io/bansidhar03/python:3.12.3
