name: cloud-api

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        id: login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          # Extract the repository name from the environment variable
          REPO_NAME=${{ github.repository }}
          # Remove any trailing dashes or invalid characters
          CLEAN_REPO_NAME=$(echo "$REPO_NAME" | sed 's/-$//')
          # Build and push the Docker image
          docker build -t ghcr.io/$CLEAN_REPO_NAME/nodejs-app:latest .
          docker push ghcr.io/$CLEAN_REPO_NAME/nodejs-app:latest
